### ISSUE TITLE
Switching from metric to imperial

### ISSUE THREAD

**Issue by Dennisd80** [jshridha/inkbird#1]
Hi,

Since i live in europe, i want to use Celsius instead of Fahrenheit. But once the pi_inkbird is connected to my ibt-4xs it switches from metric to imperial. Any way to change that?

**Comment by jshridha** [comment]
Hey - Sorry for the lack of response. I'd be happy to implement that feature. It currently defaults to Farenheit, but I'll add an environmental variable to change it to celsius. Thanks for the feedback!

**Comment by jshridha** [comment]
This is added in the latest version 1.1.1. Change your image to `jshridha/inkbird:1.1.1` and add the environmental variable `INKBIRD_TEMP_UNITS=C`
