### ISSUE TITLE
Data and Status are output to the same topic

### ISSUE THREAD

**Issue by proffalken** [jshridha/inkbird#10]
Hey,

This is a great bit of code, however I'm running into an issue when using it with platforms other than HASS as those platforms can't deal with the status updates not being JSON.

There are two solutions here as I see it:

1. Keep the topic as `inkbird/status` for all output, but change the format of the status message to `{"current_status": "online"}` or  `{"current_status": "offline"}`
2. Split the topics out to something like `inkbird/status` and `inkbird/data` so we can monitor the appropriate data

**Comment by proffalken** [comment]
Ignore me, for some reason I wasn't seeing the debug data properly, it does output to different channels!

**Comment by jshridha** [comment]
Wonderful! Glad you're finding it useful :)
