### ISSUE TITLE
New version needs releasing?

### ISSUE THREAD

**Issue by m4rkireland** [jshridha/inkbird#12]
This is really useful and thanks very much for making it available.  I can now BBQ more relaxed!

It looks like the battery issue is fixed in an unreleased version `1.2.0`.  Is there any chance of releasing this as a new version for docker to compile?

Thanks

**Comment by jshridha** [comment]
Thanks for the reminder. I'll take a look hopefully tonight and see what the state is. I may release a dev image if you don't mind testing it. My raspberry pi and inkbird are in a box somewhere from a recent move.

**Comment by m4rkireland** [comment]
Sure no problem.

**Comment by barrymossel** [comment]
> Thanks for the reminder. I'll take a look hopefully tonight and see what the state is. I may release a dev image if you don't mind testing it. My raspberry pi and inkbird are in a box somewhere from a recent move.

I would be happy to test!

**Comment by jshridha** [comment]
I just pushed out some new code, but it looks like my azure pipelines need to be migrated to github actions. Are any of you pros at that by any chance?

**Comment by jshridha** [comment]
Whoops I was totally wrong. Looks like the builds went through and are pushed to dockerhub ~10 hours ago. I'm closing this but feel free to re-open or post any more issues that may have cropped up in the new version. Enjoy the BBQ-ing!

https://hub.docker.com/r/jshridha/inkbird/tags
