### ISSUE TITLE
No mqtt data in home assistant

### ISSUE THREAD

**Issue by Dennisd80** [jshridha/inkbird#2]
Although it seems to be connected to mqtt (confirmed via broker logs) it doesn't seem to send the values. Any way to debug (sorry docker newbie) via docker. I already tried docker compose logs and i seen that is is reading the ibt-4xs correctly but i cannot see it is sending the values to mqtt.

**Comment by jshridha** [comment]
@Dennisd80 Did you close this because you're now seeing the data in home assistant? Sorry again for the late response.

**Comment by Dennisd80** [comment]
Sorry, yes. It was my noob mistake ;)
