### ISSUE TITLE
Question: Battery Level

### ISSUE THREAD

**Issue by vondraussen** [jshridha/inkbird#4]
Hi @jshridha,
which inkbird device did you use for testing?
I think I'm getting the wrong battery level here with an IBT-2X. But the probes work.
Nice work!

**Comment by jshridha** [comment]
I'm also using the IBT-2X, and there's definitely a bug in the battery level reporting. Other libraries are having the same issue. There's been some progress [here](https://github.com/sworisbreathing/go-ibbq/issues/2#issuecomment-650725433) that I'm hoping to implement.
